[package]
name = "card-sim"
version = "0.1.0"
edition = "2021"

[dependencies]
num = "0.4.1"
rand = "0.8.5"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
